<?php
declare(strict_types=1);
#=========================================#
# Plugin Custom NPC Made By HighestDreams #
#=========================================#
namespace HighestDreams\CustomNPC\Entity;
use HighestDreams\CustomNPC\NPC; 
use pocketmine\player\Player;
use pocketmine\level\Level;
use pocketmine\entity\Location;
use pocketmine\entity\Skin;
use pocketmine\world\World;
use pocketmine\entity\Entity;
use pocketmine\entity\Human;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\FloatTag;

class CustomNPC extends Human
{
    public function __construct(NPC $plugin, World $level, CompoundTag $nbt)
    {
       $this->plugin = $plugin;
       $this->level = $level;
       $this->nbt = $nbt;
        parent::__construct($level, $nbt);
        if (!$this->namedtag->hasTag("Scale", FloatTag::class)) {
            $this->namedtag->setFloat("Scale", 1.0, true);
        }
        $this->getDataPropertyManager()->setFloat(Entity::DATA_SCALE, $this->namedtag->getFloat("Scale"));
    }

    /**
     * @return bool
     */
    public function canBeMovedByCurrents(): bool
    {
        return false;
    }

    /**
     * @return bool
     */
    public function hasMovementUpdate(): bool
    {
        return false;
    }

    public function saveNBT(): CompoundTag
    {
        parent::saveNBT(); // TODO: Change the autogenerated stub
        $scale = $this->getDataPropertyManager()->getFloat(Entity::DATA_SCALE);
        $this->namedtag->setFloat("Scale", $scale, true);
    }
}